language: c

matrix:
  include:
    - env: TEST=MAIN GHC_VER=8.6.3 BUILD=CABAL CABAL_VER=2.4
      addons:
        apt:
          packages:
            - cabal-install-2.4
            - ghc-8.6.3
            - texlive-binaries
          sources:
            - hvr-ghc

install:
  - mkdir -p ~/.agda/libs/cubical
  - printf "name:" > ~/.agda/libs/cubical/cubical.agda-lib
  - printf " cubical" >> ~/.agda/libs/cubical/cubical.agda-lib
  - printf "cubical" > ~/.agda/defaults
  - printf "$HOME/.agda/libs/cubical/cubical.agda-lib" > ~/.agda/libraries
  - git clone git://github.com/agda/agda && cd agda
  - cabal sandbox init
  - cabal install
  - cd ..

script:
  - ./.cabal-sandbox/bin/agda Infinity/Cubical.agda
