language: generic

cache:
  directories:
  - $HOME/.stack

before_install:
  - mkdir -p ~/.local/bin
  - ARCH=https://www.stackage.org/stack/linux-x86_64
  - travis_retry curl -L $ARCH | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
  - export PATH=/opt/ghc/$GHC_VER/bin:/opt/cabal/$CABAL_VER/bin:$PATH;
  - export PATH=$HOME/.local/bin:$PATH;

install:
  - mkdir -p ~/.agda/libs/cubical
  - printf "name:" > ~/.agda/libs/cubical/cubical.agda-lib
  - printf " cubical" >> ~/.agda/libs/cubical/cubical.agda-lib
  - printf "cubical" > ~/.agda/defaults
  - printf "$HOME/.agda/libs/cubical/cubical.agda-lib" > ~/.agda/libraries
  - git clone --single-branch --branch master git://github.com/agda/agda && cd agda
  - stack build --stack-yaml stack-8.6.3.yaml
  - AGDA=./agda/.stack-work/install/x86_64-linux/ghc-8.6.3/8.6.3/bin/agda
  - cd ..

script:
  - ls ./agda/
  - ls ./agda/.stack-work/dist/
  - ls ./agda/.stack-work/dist/x86_64-linux
  - ls ./agda/.stack-work/install
  - ls ./agda/.stack-work/install/x86_64-linux
  - ls ./agda/.stack-work/install/x86_64-linux/ghc-8.6.3
  - ls ./agda/.stack-work/install/x86_64-linux/ghc-8.6.3/8.6.3
  - ls ./agda/.stack-work/install/x86_64-linux/ghc-8.6.3/8.6.3/bin/
  - $AGDA Infinity/Cubical.agda

branches:
  only:
    - master

