language: c

sudo: required

cache:
  directories:
  - $HOME/.stack

matrix:
  include:
    - env: GHC_VER=8.6.3 CABAL_VER=2.4
      addons:
        apt:
          packages:
            - cabal-install-2.4
            - ghc-8.6.3
            - texlive-binaries
          sources:
            - hvr-ghc

before_install:
  - mkdir -p ~/.local/bin
  - ARCH=https://www.stackage.org/stack/linux-x86_64
  - travis_retry curl -L $ARCH | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
  - export PATH=/opt/ghc/$GHC_VER/bin:/opt/cabal/$CABAL_VER/bin:$PATH;
  - export PATH=$HOME/.local/bin:$PATH;

install:
  - mkdir -p ~/.agda/libs/cubical
  - printf "name:" > ~/.agda/libs/cubical/cubical.agda-lib
  - printf " cubical" >> ~/.agda/libs/cubical/cubical.agda-lib
  - printf "cubical" > ~/.agda/defaults
  - printf "$HOME/.agda/libs/cubical/cubical.agda-lib" > ~/.agda/libraries
  - stack build
  - AGDA=$(stack path --local-install-root)/bin/agda
  - cd ..

script:
  - $AGDA Infinity/Cubical.agda

branches:
  only:
    - master

